/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  User as PrismaUser,
  Profile as PrismaProfile,
} from "@prisma/client";
import { LoginUserInput } from "../LoginUserInput";
import { LoginUserOutput } from "../LoginUserOutput";
import { RegisterUserInput } from "../RegisterUserInput";
import { RegisterUserOutput } from "../RegisterUserOutput";

export class UserServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.UserCountArgs, "select">): Promise<number> {
    return this.prisma.user.count(args);
  }

  async users(args: Prisma.UserFindManyArgs): Promise<PrismaUser[]> {
    return this.prisma.user.findMany(args);
  }
  async user(args: Prisma.UserFindUniqueArgs): Promise<PrismaUser | null> {
    return this.prisma.user.findUnique(args);
  }
  async createUser(args: Prisma.UserCreateArgs): Promise<PrismaUser> {
    return this.prisma.user.create(args);
  }
  async updateUser(args: Prisma.UserUpdateArgs): Promise<PrismaUser> {
    return this.prisma.user.update(args);
  }
  async deleteUser(args: Prisma.UserDeleteArgs): Promise<PrismaUser> {
    return this.prisma.user.delete(args);
  }

  async findProfiles(
    parentId: string,
    args: Prisma.ProfileFindManyArgs
  ): Promise<PrismaProfile[]> {
    return this.prisma.user
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .profiles(args);
  }
  async LoginUser(args: LoginUserInput): Promise<LoginUserOutput> {
    throw new Error("Not implemented");
  }
  async RegisterUser(args: RegisterUserInput): Promise<RegisterUserOutput> {
    throw new Error("Not implemented");
  }
}
